[package]
name = "xyz"
version = "0.1.0"
edition = "2024"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
debug = "full"
strip = false
opt-level = "z"

[dependencies]
linked_list_allocator = "0.10.5"
hashbrown = "0.16.1"

[features]
dbg = []

